#!/bin/sh

#Este el el gestor de shorcuts
pgrep -x sxhkd > /dev/null || sxhkd &

#Picom es para la transparencia


#Una cosa relacionada con Java y BURP
wmname LG3D &

#Activamos la polybar
~/.config/polybar/launch.sh &

#configuraciones propias de bspwm
bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	3
bspc config window_gap          3
bspc config top_padding 	43

bspc config focused_border_color '#ff5f00'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#reglas para que las apps salgan en escritorios predeterminados y otras reglas
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#My Rule: Para que caja salga en el escritorio 8 y tiling window
#bspc rule -a Caja desktop='^8' state=floating follow=on

#Background
feh --bg-fill /home/maopiccoto/Downloads/firefox/forest.jpg

#Seguimiento de las ventanas con el raton
bspc config focus_follows_pointer true

picom --experimental-backends &
